controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#product_list:
#    path: /product
#    controller: App\Controller\ProductController::index
#    methods: GET